### ISSUE TITLE
While training on Tox21 data: "NameError: name 'io_utils' is not defined"

### ISSUE THREAD

**Issue by KacperKubara** [RexYing/gnn-model-explainer#17]
**Describe the bug**
Hi,

I am encountering a bug while training the GNN model with Tox21 data. After the model training finishes, I get an error as below. The checkpoint is not getting saved as well. What should I do?
```
Train  accuracy: 0.9083333333333333
Validation  accuracy: 0.8970588235294118
Test  accuracy: 0.9105392156862745
Best val result:  {'epoch': 700, 'loss': tensor(0.1380, device='cuda:0', grad_fn=<DivBackward0>), 'acc': 0.9044117647058824}
Test result:  {'prec': 0.8022022213711222, 'recall': 0.72627360451945, 'acc': 0.9105392156862745, 'epoch': 999}
Traceback (most recent call last):
  File "train.py", line 1179, in <module>
    main()
  File "train.py", line 1156, in main
    benchmark_task(prog_args, writer=writer)
  File "train.py", line 932, in benchmark_task
    writer=writer,
  File "train.py", line 247, in train
    plt.savefig(io_utils.gen_train_plt_name(args), dpi=600)
  File "C:\Users\kacpe\Desktop\Github\gnn-model-explainer\utils\io_utils.py", line 667, in gen_train_plt_name
    return "results/" + io_utils.gen_prefix(args) + ".png"
NameError: name 'io_utils' is not defined
```
**To Reproduce**
1. Train the model on Tox data

**Platform (please complete the following information):**
 - Windows 10
- Python 3.7

**Comment by hnaik** [comment]
Submitted a PR @ https://github.com/RexYing/gnn-model-explainer/pull/20
