### ISSUE TITLE
Generating Explanations for REDDIT-BINARY and Mutag dataset

### ISSUE THREAD

**Issue by seungjun45** [RexYing/gnn-model-explainer#27]
Hi,

It seems the default setting of objective for training GCN model for 'benchmark datasets' (i.e, REDDIT, Mutag, etc) is 'Graph Classification'. It is far different from 'syn1~5' dataset which are set as 'Node Classification' in codes by default.

So I tried to generate explanations for REDDIT & Mutag with :
**python -W ignore explainer_main.py --bmname=REDDIT-BINARY --gpu --graph-mode
python -W ignore explainer_main.py --bmname=Mutagenicity --gpu --graph-mode**

but both trial gives me errors:
Traceback (most recent call last):
  File "explainer_main.py", line 316, in <module>
    main()
  File "explainer_main.py", line 280, in main
    explainer.explain_graphs(graph_indices=[1, 2, 3, 4])
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/explainer/explain.py", line 363, in explain_graphs
    masked_adj = self.explain(node_idx=0, graph_idx=graph_idx, graph_mode=True)
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/explainer/explain.py", line 172, in explain
    node_idx_new, epoch, label=single_subgraph_label
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/explainer/explain.py", line 966, in log_masked_adj
    args=self.args,
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/utils/io_utils.py", line 316, in log_graph
    raise Exception("empty edge")
Exception: empty edge
Traceback (most recent call last):
  File "explainer_main.py", line 316, in <module>
    main()
  File "explainer_main.py", line 280, in main
    explainer.explain_graphs(graph_indices=[1, 2, 3, 4])
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/explainer/explain.py", line 396, in explain_graphs
    args=self.args
  File "/mnt/server5_hard1/seungjun/gnn-model-explainer/utils/io_utils.py", line 347, in log_graph
    alpha=0.8,
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 123, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 336, in draw_networkx
    draw_networkx_edges(G, pos, arrows=arrows, **edge_kwds)
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 684, in draw_networkx_edges
    alpha=alpha,
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/matplotlib/collections.py", line 1378, in __init__
    colors = mcolors.to_rgba_array(colors)
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/matplotlib/colors.py", line 341, in to_rgba_array
    return np.array([to_rgba(cc, alpha) for cc in c])
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/matplotlib/colors.py", line 341, in <listcomp>
    return np.array([to_rgba(cc, alpha) for cc in c])
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/matplotlib/colors.py", line 189, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/cilab5/anaconda3/envs/sj_gnn_explainer/lib/python3.6/site-packages/matplotlib/colors.py", line 263, in _to_rgba_no_colorcycle
    raise ValueError(f"Invalid RGBA argument: {orig_c!r}")
ValueError: Invalid RGBA argument: tensor(1., dtype=torch.float64)

**It would be really grateful if I can find out how to generate explanations for 'benchmark datasets' :)**

**Comment by seungjun45** [comment]
if edge_vmax is None:
        edge_vmax = statistics.median_high(
            [d for (u, v, d) in Gc.edges(data="weight", default=1)]
        )
    min_color = min([d for (u, v, d) in Gc.edges(data="weight", default=1)])
    # color range: gray to black
    if type(edge_vmax) is torch.Tensor:
        edge_vmax=edge_vmax.item()
    edge_vmin = 2 * min_color - edge_vmax
    nx.draw(
        Gc,
        pos=pos_layout,
        with_labels=False,
        font_size=4,
        labels=feat_labels,
        node_color=node_colors,
        vmin=0,
        vmax=vmax,
        cmap=cmap,
        edge_color=edge_colors,
        edge_cmap=plt.get_cmap("Greys"),
        edge_vmin=edge_vmin,
        edge_vmax=edge_vmax,
        width=1.0,
        node_size=50,
        alpha=0.8,
    )

**Comment by seungjun45** [comment]
Solved :)

**Comment by seungjun45** [comment]
if type(edge_vmax) is torch.Tensor:
        edge_vmax=edge_vmax.item()
        
    if type(min_color) is torch.Tensor:
        min_color=min_color.item()

**Comment by seungjun45** [comment]
utils/io_utils.py

def denoise_graph(adj, node_idx, feat=None, label=None, threshold=None, threshold_num=None, max_component=True):
    
    if type(adj) is torch.Tensor:
        adj=adj.detach().numpy()
        
    num_nodes = adj.shape[-1]
    G = nx.Graph()
    G.add_nodes_from(range(num_nodes))
    G.nodes[node_idx]["self"] = 1
...

**Comment by seungjun45** [comment]
+ because gradient values in adjacency matrix are very incremental, this often occurs "empty edge" error whenever calling "log_adj_grad(...)" in explain.py, line871. So i would recommend to set its threshold from 0.0003 to 0.0000

explainer/explain.py (line 916)

 if self.graph_mode:
            print("GRAPH model")
            G = io_utils.denoise_graph(
                adj_grad,
                node_idx,
                feat=self.x[0],
                threshold=0.0000,  # threshold_num=20,
                max_component=True,
            )

**Comment by HennyJie** [comment]
I also met with this same error when running explanation on MUTAG: 

python -W ignore explainer_main.py --bmname=MUTAG --graph-mode
> ValueError: Invalid RGBA argument: tensor(1., dtype=torch.float64)

I tried the solution proposed by sengjun45 that change the threshold to 0.0000, but it does not work for me. Do you possibly have any ideas on this? @RexYing 

Thanks very much in advance!

**Comment by Liyiqiao** [comment]
@HennyJie Do you figure out how to deal with the error:
ValueError: Invalid RGBA argument: tensor(1., dtype=torch.float64)
I also get this error, when I try to run GNNExplainer on MUTAG

**Comment by awezmm** [comment]
Any update on this?

**Comment by awezmm** [comment]
I was able to resolve this issue by just inserting:

```python
if torch.is_tensor(edge_colors[0]):
    print(edge_colors)
    edge_colors = [x.cpu().detach().numpy().tolist() for x in edge_colors]
    print("changed edge color to list type")
    print(edge_colors)
````
right before line 330 in ```utils/io_utils.py```. I am not sure if this a proper solution as I am only converting the tensor type elements to list type.
