### ISSUE TITLE
Where can I find ppi and enron dataset？

### ISSUE THREAD

**Issue by zionzheng** [RexYing/gnn-model-explainer#5]
**Describe the bug**
hi-union-ppi.tsv and enron_slice_0.pkl are not found.

And when I use --bmname=[REDDIT-BINARY/Mutagenicity/Tox21_AHR],nothing happened，no ckpt exitsted.Where should I put these three datasets when they were downloaded manually.

**Platform**
 - OS: [e.g. Windows]
 - Python [e.g. 3.7]
 - Version [e.g. latest]

**Comment by RexYing** [comment]
The REDDIT-BINARY/Mutagenicity/Tox21_AHR can be found at https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

**Comment by zionzheng** [comment]
> The REDDIT-BINARY/Mutagenicity/Tox21_AHR can be found at https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets

Thanks for your response.But after  downloading these datasets and retraining the models
,I still cannot find ckpt or pth.tar of REDDIT-BINARY/Mutagenicity/Tox21_AHR models.
```
>python explainer_main.py --bmname=REDDIT-BINARY --gpu


CUDA 0
loading model
ckpt\REDDIT-BINARY_base_h20_o20.pth.tar
Checkpoint does not exist!
Checked path -- ckpt\REDDIT-BINARY_base_h20_o20.pth.tar
Make sure you have provided the correct path!
You may have forgotten to train a model for this dataset.

To train one of the paper's models, run the following
>> python train.py --dataset=DATASET_NAME

Traceback (most recent call last):
  File "explainer_main.py", line 316, in <module>
    main()
  File "explainer_main.py", line 193, in main
    ckpt = io_utils.load_ckpt(prog_args)
  File "C:\Users\Administrator\Desktop\gnn-model-explainer\utils\io_utils.py", line 124, in load_ckpt
    raise Exception("File not found.")
Exception: File not found.
```

**Comment by Lianlii** [comment]
Maybe you don’t train the model before explain it

**Comment by mina19** [comment]
I'm having similar problems.
When I try running "python train.py --dataset=ppi_essential" I get an error that the file hi-union-ppi.tsv does not exist. Where can I get this file?

**Comment by zzzlllzzl** [comment]
> 我也有类似的问题。当我尝试运行“python train.py --dataset=ppi_essential”时，我收到一个错误，指出文件 hi-union-ppi.tsv 不存在。我在哪里可以得到这个文件？

请问这个问题有解决吗
